// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7GlN-cwnKbrIXdATLPvR8g3F4jA26Kio',
    appId: '1:631059877383:web:598ca88a482c24d97fe4a2',
    messagingSenderId: '631059877383',
    projectId: 'spendly360',
    authDomain: 'spendly360.firebaseapp.com',
    storageBucket: 'spendly360.firebasestorage.app',
    measurementId: 'G-DLJ2WHEBG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIgj9BjzxCxS6jbf3FZCdoVAdZtZamRU',
    appId: '1:631059877383:android:0ba139d26e27c4997fe4a2',
    messagingSenderId: '631059877383',
    projectId: 'spendly360',
    storageBucket: 'spendly360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-JCL3ANvjZfmJx8kF7UGEa02gwBkxU-c',
    appId: '1:631059877383:ios:1dc3ea923522dc7d7fe4a2',
    messagingSenderId: '631059877383',
    projectId: 'spendly360',
    storageBucket: 'spendly360.firebasestorage.app',
    iosClientId: '631059877383-60r5t8md9d3uce3497tbo0hs897a1sid.apps.googleusercontent.com',
    iosBundleId: 'com.spendly.spendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-JCL3ANvjZfmJx8kF7UGEa02gwBkxU-c',
    appId: '1:631059877383:ios:1dc3ea923522dc7d7fe4a2',
    messagingSenderId: '631059877383',
    projectId: 'spendly360',
    storageBucket: 'spendly360.firebasestorage.app',
    iosClientId: '631059877383-60r5t8md9d3uce3497tbo0hs897a1sid.apps.googleusercontent.com',
    iosBundleId: 'com.spendly.spendly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7GlN-cwnKbrIXdATLPvR8g3F4jA26Kio',
    appId: '1:631059877383:web:fd4ffedc13ff675d7fe4a2',
    messagingSenderId: '631059877383',
    projectId: 'spendly360',
    authDomain: 'spendly360.firebaseapp.com',
    storageBucket: 'spendly360.firebasestorage.app',
    measurementId: 'G-PMKMC9NQ8Z',
  );
}
